build-mac:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install pyinstaller PyQt6 biopython

      - name: Build APP
        run: pyinstaller --onefile --windowed --add-data "sangerseq-full2.py:." sangerseq_gui.py

      - name: Upload APP
        uses: actions/upload-artifact@v4
        with:
          name: SangerSeq-Mac
          path: dist/sangerseq_gui
